name: Periodic re-deploy of pages

on: 
  push:
  pull_request:
  schedule:
    # refresh pages once per week on Wednesdays
    - cron: '5 5 * * 3'

jobs:
  build:
    name: Check-out and trigger re-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457
      - name: Perform dummy commit 
        run: |
          git config --global user.name 'Dominik Stadler'
          git config --global user.email 'dominik.stadler@gmx.at'
          git commit -m 'rebuild pages' --allow-empty
          git push origin gh-pages
